# Setup
title:       Miftahul Jannaty
tagline:      Mahasiswi Sistem Informasi UIN Sultan Syarif Kasim Riau
baseurl:      "Miftahul-Jannaty.github.io"
paginate:     1

# About/contact
author:
  name:       Miftahul Jannaty
  url:        "http://Miftahul-Jannaty.github.io"

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
